#!/usr/bin/env node
/**
 * Generate public/sitemap.xml and public/robots.txt for the configured origin.
 *
 * Why this exists
 * ---------------
 * `src/components/seo/Seo.tsx` already builds every canonical URL from
 * `config.siteUrl`, which is driven by `VITE_SITE_URL`. The static artefacts
 * did not: sitemap.xml, robots.txt and index.html all hardcoded
 * `https://affiliate-hub.vercel.app`.
 *
 * Setting `VITE_SITE_URL` therefore changed the canonicals a crawler read on
 * the page while the sitemap kept pointing at a different host. A sitemap that
 * advertises the wrong origin is worse than no sitemap — it sends crawlers to
 * a host that is not the site. This script makes the two agree by generating
 * the static files from the same variable.
 *
 * The committed copies are the output for the default configuration, so the
 * repository still contains a valid sitemap before anyone runs a build.
 */

import fs from 'node:fs';
import { DEFAULT_SITE_URL, DISALLOWED, ROUTES } from './site-config.mjs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Resolve the site URL.
 *
 * Reads `VITE_SITE_URL` from the environment, then from the mode-specific and
 * base `.env` files, in the same precedence Vite itself uses. Falling back to a
 * silent default would reproduce the original bug.
 */
function resolveSiteUrl(mode) {
  if (process.env.VITE_SITE_URL) return process.env.VITE_SITE_URL;

  const files = [`.env.${mode}.local`, `.env.${mode}`, '.env.local', '.env'];
  for (const file of files) {
    const full = path.join(root, file);
    if (!fs.existsSync(full)) continue;
    for (const line of fs.readFileSync(full, 'utf8').split('\n')) {
      const match = line.match(/^\s*VITE_SITE_URL\s*=\s*(.+?)\s*$/);
      if (match) return match[1].replace(/^["']|["']$/g, '');
    }
  }
  return undefined;
}

const mode = process.argv[2] ?? 'production';
const raw = resolveSiteUrl(mode);

const siteUrl = raw ?? DEFAULT_SITE_URL;

if (!raw) {
  console.warn(
    `  warning: VITE_SITE_URL is not set — using the default ${DEFAULT_SITE_URL}.\n` +
      '  Set it in .env for a real deployment, or the sitemap and canonicals will\n' +
      '  both advertise a host that is not your site.',
  );
}

let base;
try {
  base = new URL(siteUrl);
} catch {
  console.error(`\n  VITE_SITE_URL is not a valid absolute URL: ${siteUrl}\n`);
  process.exit(1);
}

if (base.protocol !== 'https:') {
  console.warn(`  warning: VITE_SITE_URL is ${base.protocol}// — production should be https`);
}

const origin = base.origin.replace(/\/+$/, '');
const today = new Date().toISOString().slice(0, 10);

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Generated by scripts/generate-sitemap.mjs — do not edit by hand.

  Origin: ${origin} (from VITE_SITE_URL, mode "${mode}")
  lastmod: ${today}

  Edit the route list in that script instead. Regenerate with
  "npm run sitemap", which the build also runs.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${ROUTES.map(
  (r) => `  <url>
    <loc>${origin}${r.path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${r.changefreq}</changefreq>
    <priority>${r.priority}</priority>
  </url>`,
).join('\n')}
</urlset>
`;

const robots = `# Generated by scripts/generate-sitemap.mjs — do not edit by hand.
# Origin: ${origin} (from VITE_SITE_URL, mode "${mode}")

User-agent: *

# Authenticated app routes. They render behind a route guard, so a crawler
# would fetch an empty shell and index thin duplicate content.
${DISALLOWED.map((r) => `Disallow: ${r}`).join('\n')}

# API surface — machine endpoints, not content.
Disallow: /api/

${ROUTES.map((r) => `Allow: ${r.path === '/' ? '/' : r.path}`).join('\n')}

Sitemap: ${origin}/sitemap.xml
`;

// Only write when executed directly. Tests import ROUTES and DISALLOWED to
// assert they still match the route guards in src/App.tsx; importing must not
// rewrite tracked files as a side effect.
const invokedDirectly = process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);

if (invokedDirectly) {
  fs.mkdirSync(path.join(root, 'public'), { recursive: true });
  fs.writeFileSync(path.join(root, 'public/sitemap.xml'), sitemap);
  fs.writeFileSync(path.join(root, 'public/robots.txt'), robots);

  console.log(`  sitemap: ${ROUTES.length} urls, ${DISALLOWED.length} disallowed → ${origin}`);
}


